name: 翻译程序跨平台打包

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: 设置Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'

    # 修复依赖安装步骤，直接使用requirements.txt
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        if [ "${{ matrix.os }}" = "macos-latest" ]; then
          brew install python-tk
        fi

    - name: 打包程序
      run: |
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          pyinstaller --onefile --windowed --name "实时翻译助手" *.py
        else
          pyinstaller --onefile --windowed --name "实时翻译助手" *.py
        fi

    - name: 上传打包产物
      uses: actions/upload-artifact@v4
      with:
        name: 翻译助手-${{ matrix.os }}
        path: |
          dist/
          !dist/_internal
