name: 翻译程序跨平台打包

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: 设置Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: 安装依赖
      # 使用GitHub Actions的条件语法替代脚本内的if判断
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      # macOS额外安装步骤单独写
      if: matrix.os == 'windows-latest'

    - name: 安装依赖 (macOS)
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        brew install python-tk
      if: matrix.os == 'macos-latest'

    - name: 打包程序 (Windows)
      run: |
        pyinstaller --onefile --windowed --name "实时翻译助手" *.py
      if: matrix.os == 'windows-latest'

    - name: 打包程序 (macOS)
      run: |
        pyinstaller --onefile --windowed --name "实时翻译助手" *.py
      if: matrix.os == 'macos-latest'

    - name: 上传打包产物
      uses: actions/upload-artifact@v4
      with:
        name: 翻译助手-${{ matrix.os }}
        path: |
          dist/
          !dist/_internal
