name: 翻译程序跨平台打包

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4

    - name: 设置Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: 安装Windows依赖
      if: matrix.os == 'windows-latest'
      run: |
        choco install openssl
        echo "C:\Program Files\OpenSSL\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8

    - name: 安装macOS依赖
      if: matrix.os == 'macos-latest'
      run: |
        brew install openssl
        brew install python-tk
        echo "export PATH=/usr/local/opt/openssl/bin:$PATH" >> ~/.bash_profile

    - name: 安装项目依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 关键修复：明确指定你的Python文件名（替换为实际文件名）
    - name: 打包程序 (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        pyinstaller --onefile --windowed --name "实时翻译助手" translator.py  # 假设文件名为translator.py

    - name: 打包程序 (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        pyinstaller --onefile --windowed --name "实时翻译助手" translator.py  # 假设文件名为translator.py

    - name: 上传打包产物
      uses: actions/upload-artifact@v4
      with:
        name: 翻译助手-${{ matrix.os }}
        path: dist/
